project:
  type: book
  output-dir: docs

book:
  title: "Data Manual"
  subtitle: "Data Analyst Tasks and Utilities"
  author: Office of System Performance
  date: last-modified
  page-navigation: true
  chapters:
    - index.qmd
    - part: Routine Reports
      chapters:
        - 01-ReportTimelines.qmd
        - reports-pdf.qmd
        - 02-core-reports.qmd
        - 03-BI-Solution-Data-Quality.qmd
    - part: Codebooks
      chapters:
        - 05-interRAI-code.qmd
    - part: Other Data Tasks
      chapters:
        - 06-Compass-Data-Workflow.qmd
        - 10-Troubleshooting.qmd
        - 11-Visualizations-in-R.qmd

  sidebar:
    background: "#f9f9f9"
    logo: "images/logo.png"
    pinned: true
    align: center
    style: docked
    collapse-level: 2

format:
  html:
    theme: [cosmo, theme.scss]
    # css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    lightbox: true
    warning: false
    message: false
    embed-resources: true
    numbered-sections: true
    other-links:
      - text: Leave us feedback
        href: https://www.research.net/r/ManualFeedback


page-footer:
  right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  left: "&copy; CC-By Compass, 2024"

execute:
  freeze: auto

