project:
  type: website
  output-dir: docs
  
website:
  title: "Data Manual"

  #navbar:
  #  background: "#f9f9f9"

  sidebar:
    background: "#f9f9f9"
    logo: "images/logo.png"
    pinned: true
    align: center
    style: docked
    collapse-level: 2
    contents:
      - index.qmd
      - section: Routine Reports
        contents:
          - 01-ReportTimelines.qmd
         # - reports-pdf.qmd
          - 02-core-reports.qmd
          - 03-BI-Solution-Data-Quality.qmd
      - section: Codebooks
        contents:
          - 05-interRAI-code.qmd
      - section: Other Data Tasks
        contents:
          - 06-Compass-Data-Workflow.qmd
          - ExternalTutorials.qmd
          - 10-Troubleshooting.qmd
          - 11-Visualizations-in-R.qmd
format:
  html:
    theme: [cosmo, theme.scss]
    # css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    lightbox: true
    warning: false
    message: false
    embed-resources: true
    numbered-sections: true
    other-links:
      - text: Leave us feedback
        href: https://www.research.net/r/ManualFeedback

page-footer:
  right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  left: "&copy; CC-By Compass, 2024"

execute:
  freeze: auto

