project:
  type: website
  output-dir: docs

website:
  title: "Compass Tutorials"

  sidebar:
    background: "#f9f9f9"
    logo: "images/logo.png"
    pinned: true
    align: center
    style: docked
    contents:
      - href: index.qmd
        text: Welcome
      - href: filedispo.qmd
        text: File Disposition
      - href: closingsummary.qmd
        text: Closing Summary

style: "docked"

format:
  html:
    theme: [cosmo, theme.scss]
    # css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    lightbox: true

page-footer:
  right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  left: "&copy; CC-By Compass, 2024"

execute:
  freeze: auto

