project:
  type: website
  output-dir: docs

website:
  title: "Compass Tutorials"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    style: docked
    contents:
      - href: index.qmd
        text: Welcome
      - href: schedule.qmd
        text: File Disposition
      - href: materials.qmd
        text: Closing Summary

style: "docked"

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap

page-footer:
  right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  left: "&copy; CC-By Compass, 2024"

execute:
  freeze: auto

